"""baseline schema

Revision ID: 4e794452fecc
Revises: 
Create Date: 2026-08-28 01:01:02.383435
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# Text and postgresql are imported unconditionally because autogenerate renders
# the models' JSON().with_variant(JSONB, "postgresql") columns as
# postgresql.JSONB(astext_type=Text()). Without them a generated revision
# raises NameError partway through, having already created some tables.

revision: str = '4e794452fecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('last4', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('family')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('prompt_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('business_problem', sa.Text(), nullable=False),
    sa.Column('target_domain', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('audience', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('output_format', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('selected_model_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_prompt_runs_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_runs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_runs_status'), ['status'], unique=False)

    op.create_table('consensus_prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_merged_content', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('section_provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('conflicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reinforcements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('optimization_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('tokens_saved', sa.Integer(), nullable=False),
    sa.Column('improvement_over_best', sa.Float(), nullable=True),
    sa.Column('vector_point_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consensus_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consensus_prompts_run_id'), ['run_id'], unique=True)

    op.create_table('execution_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_execution_logs_run_stage', ['run_id', 'stage'], unique=False)

    op.create_table('prompt_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('seed_prompt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['prompt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_run_model', ['run_id', 'model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_candidates_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_candidates_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_candidates_run_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_candidates_overall_score'))
        batch_op.drop_index('ix_candidates_run_model')

    op.drop_table('prompt_candidates')
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_logs_run_stage')
        batch_op.drop_index(batch_op.f('ix_execution_logs_run_id'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_created_at'))

    op.drop_table('execution_logs')
    with op.batch_alter_table('consensus_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consensus_prompts_run_id'))

    op.drop_table('consensus_prompts')
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_runs_status'))
        batch_op.drop_index(batch_op.f('ix_prompt_runs_owner_id'))
        batch_op.drop_index('ix_prompt_runs_owner_created')
        batch_op.drop_index(batch_op.f('ix_prompt_runs_created_at'))

    op.drop_table('prompt_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
