"""Export the Elite Consensus Prompt into deployable artefacts."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any
from xml.sax.saxutils import escape

import yaml

from app.models.domain import ConsensusPrompt, PromptRun
from app.models.schemas import ExportFormat


@dataclass
class ExportArtifact:
    filename: str
    media_type: str
    content: str


def _payload(
    run: PromptRun, consensus: ConsensusPrompt, include_evaluation: bool
) -> dict[str, Any]:
    document: dict[str, Any] = {
        "run_id": str(run.id),
        "title": run.title,
        "target_domain": run.target_domain,
        "business_problem": run.business_problem,
        "constraints": run.constraints,
        "requirements": run.requirements,
        "generated_at": (run.completed_at or datetime.now(timezone.utc)).isoformat(),
        "models": run.selected_model_ids,
        "prompt": consensus.content,
        "token_count": consensus.token_count,
        "overall_score": consensus.overall_score,
    }
    if include_evaluation:
        document["evaluation"] = consensus.evaluation
        document["metrics"] = consensus.metrics
        document["section_provenance"] = consensus.section_provenance
        document["conflicts"] = consensus.conflicts
        document["optimization_report"] = consensus.optimization_report
    return document


def _slug(value: str) -> str:
    cleaned = "".join(char if char.isalnum() else "-" for char in value.lower())
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")[:60] or "master-prompt"


def _escape_python(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def _escape_ts(text: str) -> str:
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def export_consensus(
    run: PromptRun,
    consensus: ConsensusPrompt,
    export_format: ExportFormat,
    include_evaluation: bool = True,
) -> ExportArtifact:
    slug = _slug(run.title)
    document = _payload(run, consensus, include_evaluation)

    if export_format is ExportFormat.JSON:
        return ExportArtifact(
            filename=f"{slug}.json",
            media_type="application/json",
            content=json.dumps(document, indent=2, default=str),
        )

    if export_format is ExportFormat.YAML:
        return ExportArtifact(
            filename=f"{slug}.yaml",
            media_type="application/x-yaml",
            content=yaml.safe_dump(document, sort_keys=False, allow_unicode=True),
        )

    if export_format is ExportFormat.XML:
        metrics = consensus.metrics or {}
        metric_nodes = "\n".join(
            f"    <metric name=\"{escape(key)}\">{value}</metric>"
            for key, value in metrics.items()
        )
        content = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            "<master_prompt>\n"
            f"  <title>{escape(run.title)}</title>\n"
            f"  <domain>{escape(run.target_domain)}</domain>\n"
            f"  <overall_score>{consensus.overall_score or 0}</overall_score>\n"
            f"  <metrics>\n{metric_nodes}\n  </metrics>\n"
            f"  <prompt><![CDATA[\n{consensus.content}\n]]></prompt>\n"
            "</master_prompt>\n"
        )
        return ExportArtifact(
            filename=f"{slug}.xml", media_type="application/xml", content=content
        )

    if export_format is ExportFormat.PYTHON:
        content = (
            '"""Elite Consensus Prompt generated by Master Prompt Generator.\n\n'
            f"Run: {run.id}\n"
            f"Title: {run.title}\n"
            f"Score: {consensus.overall_score}\n"
            '"""\n\n'
            "from typing import Final\n\n"
            f'MASTER_PROMPT: Final[str] = """{_escape_python(consensus.content)}"""\n\n'
            f"PROMPT_METADATA: Final[dict] = {json.dumps(document, indent=4, default=str)}\n"
        )
        return ExportArtifact(
            filename=f"{slug}.py", media_type="text/x-python", content=content
        )

    if export_format is ExportFormat.TYPESCRIPT:
        content = (
            "/**\n"
            " * Elite Consensus Prompt generated by Master Prompt Generator.\n"
            f" * Run: {run.id}\n"
            f" * Score: {consensus.overall_score}\n"
            " */\n\n"
            f"export const MASTER_PROMPT = `{_escape_ts(consensus.content)}` as const;\n\n"
            f"export const PROMPT_METADATA = {json.dumps(document, indent=2, default=str)} as const;\n"
        )
        return ExportArtifact(
            filename=f"{slug}.ts", media_type="text/plain", content=content
        )

    # Markdown (default)
    sections = [
        f"# {run.title}",
        "",
        f"- **Domain:** {run.target_domain}",
        f"- **Run id:** `{run.id}`",
        f"- **Models:** {', '.join(run.selected_model_ids) or 'n/a'}",
        f"- **Consensus score:** {consensus.overall_score}",
        f"- **Tokens:** {consensus.token_count} (saved {consensus.tokens_saved})",
        "",
        "## Elite Consensus Prompt",
        "",
        "```text",
        consensus.content.rstrip(),
        "```",
    ]

    if include_evaluation:
        metrics = consensus.metrics or {}
        sections += ["", "## Evaluation", "", "| Metric | Score |", "| --- | --- |"]
        sections += [
            f"| {key.replace('_', ' ').title()} | {value:.1f} |"
            for key, value in sorted(metrics.items())
        ]

        if consensus.section_provenance:
            sections += [
                "",
                "## Section Provenance",
                "",
                "| Section | Source | Score | Strategy | Merged from |",
                "| --- | --- | --- | --- | --- |",
            ]
            for item in consensus.section_provenance:
                merged = ", ".join(item.get("merged_from", [])) or "—"
                sections.append(
                    f"| {item.get('section')} | {item.get('source_model_name')} "
                    f"| {item.get('score')} | {item.get('strategy')} | {merged} |"
                )

        if consensus.conflicts:
            sections += ["", "## Resolved Conflicts", ""]
            sections += [
                f"- **[{item.get('kind')}] {item.get('section')}** — {item.get('resolution')}"
                for item in consensus.conflicts
            ]

    return ExportArtifact(
        filename=f"{slug}.md",
        media_type="text/markdown",
        content="\n".join(sections) + "\n",
    )
